<div class="outter-wp">
	<div class="sub-heard-part">
		<ol class="breadcrumb m-b-0">
			<li><a href="">Home</a></li>
			<li>Cadastro</li>
			<li class="active">Funcionário</li>
		</ol>
	</div>

	<div class="forms-main">
		<div class="graph-form">
			<div class="validation-form">
				<form class="form-horizontal group-border hover-stripped" role="form" method="post" action="<?php echo $this->baseUrl('/cadastro/funcionario/index')?>">
					<div class="vali-form">
						<div class="col-md-2 form-group1">
							<label class="control-label">Matrícula</label> 
							<input type="text" class="form-control" name="num_matricula" id="num_matricula" required>
						</div>
						<div class="col-md-6 form-group1">
							<label class="control-label">Nome</label> 
							<input type="text" class="form-control" name="st_nome" id="st_nome" required>
						</div>
						<div class="col-md-4 form-group1">
							<label class="control-label">CPF/CNPJ</label> 
							<input type="text" class="form-control" name="num_cpf" id="num_cpf" required>
						</div>
					</div>
					<div class="vali-form">
						<div class="col-md-2 form-group1">
							<label class="control-label">RG</label> 
							<input type="text" class="form-control" name="num_rg" id="num_rg" required>
						</div>
						<div class="col-md-2 form-group1">
							<label class="control-label">Data Nascimento</label> 
							<input type="text" class="form-control" name="dt_nascimento" id="dt_nascimento" required>
						</div>
						<div class="col-md-4 form-group1">
							<label class="control-label">CTPS</label> 
							<input type="text" class="form-control" name="num_ctps" id="num_ctps" required>
						</div>
						<div class="col-md-4 form-group1">
							<label class="control-label">CNH</label> 
							<input type="text" class="form-control" name="num_cnh" id="num_cnh" required>
						</div>

					</div>
					<div class="vali-form">

						<div class="col-md-3 form-group2">
							<label class="control-label">Estado Civil</label> 
							<select name="st_estadoCivil" id="st_estadoCivil" required>
								<option></option>
								<option value="casado">CASADO (A)</option>
								<option value="solteiro">SOLTEIRO (A)</option>
								<option value="separado">SEPARADO (A)</option>
								<option value="divorciado">DIVORCIADO (A)</option>
							</select>
						</div>
						<div class="col-md-3 form-group2">
							<label class="control-label">Cargo</label> 
							<select name="id_cargo" id="id_cargo" required>
								<option></option>
							</select>
						</div>
						<div class="col-md-4 form-group1">
							<label class="control-label">Email</label> 
							<input type="text" class="form-control" name="st_email" id="st_email">
						</div>
						<div class="col-md-2 form-group1">
							<label class="control-label">Telefone</label> 
							<input type="text" class="form-control" name="num_telefone" id="num_telefone" maxlength="15">
						</div>

					</div>
					<div class="col-md-2 form-group1">
						<label class="control-label">CEP</label> 
						<input type="text" class="form-control" name="num_cep" id="num_cep" required>
					</div>
					<div class="col-md-8 form-group1">
						<label class="control-label">Logradouro</label> 
						<input type="text" class="form-control" name="ds_logradouro" id="ds_logradouro" required>
					</div>

					<div class="col-md-2 form-group1">
						<label class="control-label">Nº</label> 
						<input type="text" class="form-control" name="num_logradouro" id="num_logradouro" required>
					</div>

					<div class="clearfix"></div>

					<div class="col-md-12 form-group1">
						<label class="control-label">Complemento</label> 
						<input type="text" class="form-control" name="ds_complemento" id="ds_complemento">
					</div>

					<div class="clearfix"></div>

					<div class="col-md-5 form-group1">
						<label class="control-label">Bairro</label> 
						<input type="text" class="form-control" name="ds_bairro" id="ds_bairro" required>
					</div>

					<div class="col-md-5 form-group1">
						<label class="control-label">Cidade</label> 
						<input type="text" class="form-control" name="ds_cidade" id="ds_cidade" required>
					</div>

					<div class="col-md-2 form-group1">
						<label class="control-label">UF</label> 
						<input type="text" name="ds_uf" id="ds_uf" required>
					</div>

					<div class="col-md-12 form-group2">
						<label class="control-label">Upload Assinatura</label> 
						<input type="file" id="ds_assinatura" name="ds_assinatura">
					</div>

					<div class="col-md-12 form-group1 ">
						<label class="control-label">Observação</label>
						<textarea name="ds_observacao" id="ds_observacao"></textarea>
					</div>
					<div class="col-md-12 form-group button-2">
						<button type="submit" class="btn btn-primary">Salvar</button>
						<a
							href="<?php echo $this->baseUrl('/cadastro/funcionario/listagem')?>">
							<button class="btn btn-red" type="button">Visualizar Cadastrados</button>
						</a>
					</div>
					<div class="clearfix"></div>
				</form>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript"
	src="<?php echo $this->baseUrl('/js/cadastro/funcionario.js')?>"> </script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl('/js/plugins/util.js')?>"> </script>

<script type="text/javascript">
	function mascara(o,f){
		v_obj=o;
		v_fun=f;
		setTimeout("execmascara()",1);
	}
	function execmascara(){
		v_obj.value=v_fun(v_obj.value);
	}
	function mtel(v){
		v=v.replace(/\D/g,"");
		v=v.replace(/^(\d{2})(\d)/g,"($1) $2");
		v=v.replace(/(\d)(\d{4})$/,"$1-$2");
		return v;
	}
	function data(v){
		v=v.replace(/\D/g,"");
		v=v.replace(/(\d{2})(\d)/,"$1/$2");
		v=v.replace(/(\d{2})(\d)/,"$1/$2");    
		return v;
	}
	function id( el ){
		return document.getElementById( el );
	}
	window.onload = function(){
		id('num_telefone').onkeypress = function(){
			mascara( this, mtel );
		},
		id('num_celular').onkeypress = function(){
			mascara( this, mtel );
		}
	}
	</script>


