<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.3.0/css/select.dataTables.min.css">



<div class="outter-wp">
        <!--/sub-heard-part-->
    <div class="sub-heard-part">
        <ol class="breadcrumb m-b-0">
            <li><a href="">Home</a></li>
            <li>Configuração</li>
            <li>Perfil</li>
            <li class="active">Listagem</li>
        </ol>
    </div>
    <div class="navbar-btn-right">
        <a href="<?php echo $this->baseUrl('/sistema/perfil/')?>">
            <button class="btn btn-green" type="button">Adicionar Perfil</button>
        </a> 
    </div>
    <?php if(!empty($this->rsPerfil)):?>
    <div class="graph">
        <div class="tables">
            <table id="example" class="display nowrap" style="width:100%">
                <thead> 
                    <tr> 
                        <th>Código</th> 
                        <th>Nome</th>
                        <th>Situação</th>
                        <th>Ação</th>
                    </tr> 
                </thead> 
                <tbody> 
                    <?php foreach ($this->rsPerfil as $list) : ?>
                        <tr> 
                            <td><?php echo $list['id_perfil'] ?></td> 
                            <td><?php echo $list['st_nome'] ?></td>
                            <td><?php echo $list['id_ativo'] == 1 ? '<strong style="color:green;">'.'ATIVO'.'</strong>':'<strong style="color:red;">'.'INATIVO'.'</strong>'; ?></td>
                            <td style="text-align: center; width:15%;">
                                <a href="<?php echo $this->baseUrl('/sistema/perfil/')?>"><span class="label label-primary" title="Editar Registro"><i class="fa fa-edit"></i></span></a>
                                <?php if($list['id_ativo']==1):?>
                                    <a href=""><span class="label label-danger" title="Inativar Registro"><i class="fa fa-times-circle"></i></span></a>
                                <?php else: ?>
                                    <a href=""><span class="label label-warning" title="Ativar Registro"><i class="fa fa-times-circle"></i></span></a>
                            <?php endif;?>
                            </td>
                        </tr> 
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php else :?>
        <div class="alert alert-danger fade in" style="text-align: center;">
            <strong>NÃO EXISTEM DADOS CADASTRADOS, CLIQUE NO BOTÃO "ADICIONAR PERFIL" PARA REALIZAR OS CADASTROS</strong>
        </div>
    <?php endif;?>
    
</div>

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/rowreorder/1.2.5/js/dataTables.rowReorder.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>

<script>
    $(document).ready(function() {
        var table = $('#example').DataTable( {
            rowReorder: {
                selector: 'td:nth-child(2)'
            },
            responsive: true
        } );
    } );
</script>