<div class="outter-wp">
	<div class="sub-heard-part">
		<ol class="breadcrumb m-b-0">
			<li><a href="">Home</a></li>
			<li>Cadastro</li>
			<li class="active">Usuário</li>
		</ol>
	</div>
		
	<div>
		<?php if(!empty($this->msg)):?>
			<div class="alert alert-success fade in">
				<button class="close" aria-hidden="true" data-dismiss="alert" type="button">x</button>
				<i class="fa-ok alert-icon s24"></i>
				<strong><?php echo $this->msg?></strong>
			</div>
		<?php endif;?>
	</div>
	
	<div class="forms-main">
		<div class="graph-form">
			<div class="validation-form">
				<form class="form-horizontal group-border hover-stripped" role="form" method="post" enctype="multipart/form-data" action="<?php echo $this->baseUrl('/cadastro/funcionario/index')?>">
					<input type="hidden" id="id_usuario" name="id_usuario" value="<?php echo $this->dadospagina['id_usuario']?>">
					<div class="vali-form">
						<div class="col-md-6 form-group1">
							<label class="control-label">Tipo Usuário</label> </br>
							<input type="radio" name="tp_usuario" id="tp_usuario" value='I'> <label>Interno</label>
							<input type="radio" name="tp_usuario" id="tp_usuario" value='E'> <label>Externo</label>
						</div>
						<div class="col-md-6 form-group2" id="user">
							<label class="control-label">Usuário</label> 
							<span id="retorno"> </span>
						</div>
					</div>
					<div class="col-md-12 form-group1">
						<label class="control-label">Login</label> 
						<input type="text" class="form-control" name="num_rg" id="num_rg" required value="<?php echo $this->dadospagina['num_rg']?>">
					</div>
					<div class="col-md-12 form-group1">
						<label class="control-label">Senha</label> 
						<input type="text" class="form-control" name="dt_nascimento" id="dt_nascimento" required value="<?php echo $this->dadospagina['dt_nascimento']?>">
					</div>
					<div class="col-md-12 form-group2">
						<label class="control-label">Perfil</label> 
						<select name="id_perfil" id="id_perfil"required>
						<option></option>
						<?php foreach ($this->rsPerfil as $args) :?>
							<option value='<?php echo $args['id_perfil']?>' <?php if($this->dadospagina['id_perfil'] == $args['id_perfil']) echo "selected"?>><?php echo $args['st_nome']?></option>
						<?php endforeach;?>
					</select>
					</div>
										
					<div class="col-md-12 form-group1 ">
						<label class="control-label">Observação</label>
						<textarea name="ds_observacao" id="ds_observacao"><?php echo $this->dadospagina['ds_observacao']?></textarea>
					</div>
					<div class="col-md-12 form-group button-2">
						<button type="submit" class="btn btn-primary">Salvar</button>
						<a
							href="<?php echo $this->baseUrl('/cadastro/funcionario/listagem')?>">
							<button class="btn btn-red" type="button">Visualizar Cadastrados</button>
						</a>
					</div>
					<div class="clearfix"></div>
				</form>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl('/js/usuario/usuario.js')?>"> </script>
<script type="text/javascript" 	src="<?php echo $this->baseUrl('/js/plugins/util.js')?>"> </script>



