<div id="content">
	<div class="content-wrapper">		
		<div class="row">
			<div class="col-lg-12 heading">
                <h1 class="page-header"><i class="ec-pencil2"></i> <strong>LISTAGEM DE USUÁRIOS</strong></h1>
                <ul id="crumb" class="breadcrumb">
                </ul>
                <div class="option-buttons">
                    <div class="btn-toolbar" role="toolbar">
                        <div class="btn-group">
                            <a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/usuario/usuario/')?>">
								<button class="btn btn-primary" type="button"><i class="st-file-add"></i> ADICIONAR USUÁRIO</button>
							</a>
                        </div>
                    </div>
                </div>
            </div>
		</div>
		
		<?php if(!empty($this->rsUsuario)):?>
		
			<div class="panel panel-default plain toggle panelClose panelRefresh">
                                <!-- Start .panel -->
                <div class="panel-heading">
                    <h4 class="panel-title">Relatório de Cadastros</h4>
                </div>
                <div class="panel-body">
                	<table id="table-object" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>Registro</th>
								<th>Nome</th>
								<th>Login</th>
								<th>Perfil</th>
								<th>Status</th>
								<th>Ação</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($this->rsUsuario as $rsUsuario) : ?>
								<tr>
                                	<td><?php echo str_pad($rsUsuario['id_usuario'], 5, "0", STR_PAD_LEFT); ?></td>
                                    <td><?php echo $rsUsuario['nm_funcionario'] ?></td>
                                    <td><?php echo $rsUsuario['st_usuario'] ?></td>
                                    <td><?php echo $rsUsuario['nm_perfil'] ?></td>
                                    <td><?php echo $rsUsuario['id_ativo'] == 1 ? 'ATIVO':'INATIVO';?></td>
                                    <td style="text-align: center;">
										<a href="<?php echo $this->baseUrl('/usuario/usuario/index/id/'.base64_encode($rsUsuario["id_funcionario"].'@'.$rsUsuario['id_usuario']))?>"><span class="fa-edit s20" title="Editar Registro"></span></a> | 
										<a href="<?php echo $this->baseUrl('/usuario/usuario/inativarregistro/id/'.base64_encode($rsUsuario["id_funcionario"].'@'.$rsUsuario['id_usuario']))?>"><span class="fa-remove s20" title="Inativar Registro"></span></a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
						</tbody>
					</table>
                </div>
    		</div>
		<?php else :?>
            <div class="alert alert-danger fade in" style="text-align: center;">
                <strong>NÃO EXISTEM USUÁRIOS CADASTRADOS, CLIQUE NO BOTÃO "ADICIONAR USUÁRIO" PARA REALIZAR OS CADASTROS</strong>
            </div>
		<?php endif;?>
	</div>
	<div class="clearfix"></div>
</div>