<!DOCTYPE HTML>
<html>
<head>
<title>Sisgerma | Sistema de Gerenciamento de Manutenção</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords"
	content="Augment Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
    Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Bootstrap Core CSS -->
<link href="<?php echo $this->baseUrl()?>/vendor/css/bootstrap.min.css"
	rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<link href="<?php echo $this->baseUrl()?>/vendor/css/style.css"
	rel='stylesheet' type='text/css' />
<!-- Graph CSS -->
<link href="<?php echo $this->baseUrl()?>/vendor/css/font-awesome.css"
	rel="stylesheet">
<!-- jQuery -->
<link
	href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400'
	rel='stylesheet' type='text/css'>
<!-- lined-icons -->
<link rel="stylesheet"
	href="<?php echo $this->baseUrl()?>/vendor/css/icon-font.min.css"
	type='text/css' />
<!-- //lined-icons -->
<script
	src="<?php echo $this->baseUrl()?>/vendor/js/jquery-1.10.2.min.js"></script>
<script src="<?php echo $this->baseUrl()?>/vendor/js/amcharts.js"></script>
<script src="<?php echo $this->baseUrl()?>/vendor/js/serial.js"></script>
<script src="<?php echo $this->baseUrl()?>/vendor/js/light.js"></script>
<script src="<?php echo $this->baseUrl()?>/vendor/js/radar.js"></script>
<link href="<?php echo $this->baseUrl()?>/vendor/css/barChart.css"
	rel='stylesheet' type='text/css' />
<link href="<?php echo $this->baseUrl()?>/vendor/css/fabochart.css"
	rel='stylesheet' type='text/css' />
<!--clock init-->
<script src="<?php echo $this->baseUrl()?>/vendor/js/css3clock.js"></script>
<!--Easy Pie Chart-->
<!--skycons-icons-->
<script src="<?php echo $this->baseUrl()?>/vendor/js/skycons.js"></script>
<script
	src="<?php echo $this->baseUrl()?>/vendor/js/jquery.easydropdown.js"></script>

<script
	src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
</head>

<body>
	<div class="page-container">
		<!--/content-inner-->
		<div class="left-content">
			<div class="inner-content">
				<!-- header-starts -->
				<div class="header-section">
					<!--menu-right-->
					<div class="top_menu">
						<div class="profile_details_left">
							<p class="logo">
								<a href=""><img id="logo" width="40%"
									src="<?php echo $this->baseUrl()?>/img/logo/rcControls.png"></a>
							</p>
						</div>
					</div>
					<!--//menu-right-->
					<div class="clearfix"></div>
				</div>
				<!-- //header-ends -->
				<div class="outter-wp">    
                    <?php echo $this->layout()->content;?>
                </div>
				<!--footer section start-->
				<footer>
					<p>
						&copy 2019 Sisgerma . All Rights Reserved | Design by <img
							id="logo" width="10%"
							src="<?php echo $this->baseUrl()?>/img/logo/raostec2.png">
					</p>
				</footer>
				<!--footer section end-->
			</div>
		</div>
		<!--//content-inner-->
		<!--/sidebar-menu-->
		<div class="sidebar-menu">
            <?php echo $this->render('menu_vertical.phtml');?>	
        </div>
		<div class="clearfix"></div>
	</div>

	<script>
        var toggle = true;
                
        $(".sidebar-icon").click(function() {                
            if (toggle) {
                $(".page-container").addClass("sidebar-collapsed").removeClass("sidebar-collapsed-back");
                $("#menu span").css({"position":"absolute"});
            } else {
                $(".page-container").removeClass("sidebar-collapsed").addClass("sidebar-collapsed-back");
                setTimeout(function() {
                    $("#menu span").css({"position":"relative"});
                }, 400);
            }
                    
            toggle = !toggle;
        });
    </script>
	<!--js -->
	<link rel="stylesheet"
		href="<?php echo $this->baseUrl()?>/vendor/css/vroom.css">
	<script type="text/javascript"
		src="<?php echo $this->baseUrl()?>/vendor/js/vroom.js"></script>
	<script type="text/javascript"
		src="<?php echo $this->baseUrl()?>/vendor/js/TweenLite.min.js"></script>
	<script type="text/javascript"
		src="<?php echo $this->baseUrl()?>/vendor/js/CSSPlugin.min.js"></script>
	<script
		src="<?php echo $this->baseUrl()?>/vendor/js/jquery.nicescroll.js"></script>
	<script src="<?php echo $this->baseUrl()?>/vendor/js/scripts.js"></script>

	<!-- Bootstrap Core JavaScript -->
	<script src="<?php echo $this->baseUrl()?>/vendor/js/bootstrap.min.js"></script>
</body>
</html>