<div id="content">
	<div class="content-wrapper">
		<div class="row">
			<!-- Start .row -->
			<!-- Start .page-header -->
			<div class="col-lg-12 heading">
				<h1 class="page-header">
					<i class="ec-user"></i> <strong>PROFILE</strong>
				</h1>
				<!-- Start .bredcrumb -->
				<ul id="crumb" class="breadcrumb">
				</ul>
				<!-- End .breadcrumb -->

			</div>
			<!-- End .page-header -->
		</div>
		<!-- End .row -->
		<div class="outlet">
			<!-- Start .outlet -->
			<!-- Page start here ( usual with .row ) -->
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
					<!-- col-lg-4 start here -->
					<div class="panel panel-default plain profile-widget">
						<!-- Start .panel -->
						<div class="panel-heading white-bg pl0 pr0">
							<img class="profile-image img-responsive"
								src="<?php echo $this->baseUrl()?>/assets/img/profile-cover.jpg"
								alt="profile cover">
						</div>
						<div class="panel-body">
							<div class="col-lg-4 col-md-4 col-sm-12">
								<div class="profile-avatar">
									<img class="img-responsive" alt="@roybarberuk"
										src="<?php echo $this->baseUrl()?>/img/fotos/usuario/<?php echo App_Identity::getIdUsuario()?>.png">
								</div>
							</div>
							<div class="col-lg-8 col-md-8 col-sm-12">
								<div class="profile-name">
                                    <?php echo strtoupper(App_Identity::get('st_usuario')) ?> <span
										class="label label-success">admin</span>
								</div>
								<div class="profile-stats-info">
									<a href="#" class="tipB" title="Views"><i class="im-eye2"></i>
										<strong>5600</strong></a> <a href="#" class="tipB"
										title="Comments"><i class="im-bubble"></i> <strong>75</strong></a>
									<a href="#" class="tipB" title="Likes"><i class="im-heart"></i>
										<strong>45</strong></a>
								</div>
							</div>
						</div>
						<div class="panel-footer white-bg">
							<ul class="profile-info">
								<li><i class="ec-mobile"></i> +234 345 887</li>
								<li><i class="ec-mail"></i> suggeelson@suggelson.com</li>
								<li><i class="im-office"></i> Web developer</li>
							</ul>
						</div>
					</div>
					<!-- End .panel -->
				</div>
				<!-- col-lg-4 end here -->
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
					<!-- col-lg-4 start here -->
					<div class="panel panel-default plain">
						<!-- Start .panel -->
						<div class="panel-heading white-bg">
							<h4 class="panel-title">
								<i class="ec-user"></i> Update info
							</h4>
						</div>
						<div class="panel-body">
							<form class="form-vertical hover-stripped" role="form">
								<div class="form-group">
									<label class="control-label">Username</label> <input
										type="text" class="form-control"
										value=" <?php echo strtoupper(App_Identity::get('st_usuario')) ?>"
										disabled> <a href="#" class="help-block color-red">Request new
										?</a>
								</div>
								<div class="form-group">
									<label class="control-label">Full name</label> <input
										type="text" class="form-control" value="Jonh Doe">
								</div>
								<div class="form-group">
									<label class="control-label">Email</label> <input type="email"
										class="form-control" value="suggeelson@suggeelson.com">
								</div>
								<div class="form-group">
									<label class="control-label">New password</label> <input
										type="password" class="form-control">
								</div>
								<div class="form-group">
									<label class="control-label">Repeat password</label> <input
										type="password" class="form-control">
								</div>
								<div class="form-group mb15">
									<button class="btn btn-primary">Change</button>
								</div>
								<!-- End .form-group  -->
							</form>
						</div>
					</div>
					<!-- End .panel -->
				</div>
				<!-- col-lg-4 end here -->
			</div>
			<!-- Page End here -->
		</div>
		<!-- End .outlet -->
	</div>
</div>