<div class="outter-wp">
	<div class="sub-heard-part">
		<ol class="breadcrumb m-b-0">
			<li><a href="<?php echo $this->baseUrl('/administrativo/painel/')?>">Home</a></li>
			<li><a href="<?php echo $this->baseUrl('/roteiro/painel/')?>">Roteiro</a></li>
			<li class="active">Painel</li>
		</ol>
	</div>

	<div class="forms-main">
		<div class="graph-form">
			<div class="validation-form">
				<div class="vali-form">
					<div class="col-md-12 form-group2">
						<label class="control-label">Clientes</label>
						<select name="id_cliente" id="id_cliente" required>
							<option></option>
						</select>
					</div>
					<div class="col-md-12 form-group1">
						<div class="col-md-12 inner-grid-button">
							<div class="grid-1">
								<label class="control-label"><h3> Roteiros de Manutenção </h3></label>
								<?php foreach($this->rsRoteiro as $roteiro): ?>
									<a href="<?php echo $this->baseUrl().'/roteiro/'.$roteiro['st_sigla'] ?>"><button class="facebook"><?php echo $roteiro['st_sigla'] ?> </button></a>
								<?php endforeach; ?>
							</div>
						</div>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
</div>

