<div class="outter-wp">
	<div class="sub-heard-part">
		<ol class="breadcrumb m-b-0">
			<li><a href="<?php echo $this->baseUrl('/administrativo/painel/')?>">Home</a></li>
			<li><a href="<?php echo $this->baseUrl('/roteiro/painel/')?>">Roteiro</a></li>
			<li class="active">Painel</li>
		</ol>
	</div>

	<div class="forms-main">
		<div class="graph-form">
			<div class="validation-form">
				<div class="vali-form">
					<div class="col-md-12 form-group2">
						<label class="control-label">Clientes</label> 
						<select name="id_cliente" id="id_cliente" required>
							<option></option>
							<?php foreach ($this->rsCliente as $args) :?>
    							<option value='<?php echo $args['id_cliente']?>'><?php echo $args['st_nome']?></option>
    						<?php endforeach;?>
						</select>
					</div>
					<div class="col-md-12 form-group1" id='grid_roteiro'>
						<div class="col-md-12 inner-grid-button">
							<div class="grid-1">
								<label class="control-label"><h3>Roteiros de Manutenção</h3></label>
								<span id="retorno"> </span>
							</div>
						</div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl('/js/roteiro/painel.js')?>"> </script>

