<!DOCTYPE html>

<html>
<head>
<title>SISGERMA | Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="keywords"
	content="Augment Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
    Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="<?php echo $this->baseUrl()?>/vendor/css/bootstrap.min.css"
	rel="stylesheet" />
<link href="<?php echo $this->baseUrl()?>/vendor/css/style.css"
	rel='stylesheet' type='text/css' />
<link href="<?php echo $this->baseUrl()?>/vendor/css/font-awesome.css"
	rel="stylesheet" />
<link
	href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400'
	rel='stylesheet' type='text/css' />
<link href="<?php echo $this->baseUrl()?>/vendor/css/icon-font.min.css"
	rel="stylesheet" />
<script
	src="<?php echo $this->baseUrl()?>/vendor/js/jquery-1.10.2.min.js"></script>
<link rel="icon"
	href="<?php echo $this->baseUrl()?>/assets/img/ico/favicon.ico"
	type="image/png">
</head>

<body>
	<div class="error_page">
		<div class="error-top">
			<h2 class="inner-tittle page">SISGERMA</h2>
			<div class="login">
				<h3 class="inner-tittle t-inner">
					<img id="logo" width="50%"
						src="<?php echo $this->baseUrl()?>/img/logo/rcControls.png">
				</h3>
				<form action="<?php echo $this->baseUrl()?>/auth" id="login-form"
					role="form" method="post">
					<div
						class="form-group{{ $errors->has('text') ? ' has-error' : '' }}">
						<input id="usuario" type="text" class="text" name="usuario"
							placeholder="Login" required autofocus>
					</div>

					<div
						class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
						<input id="senha" type="password" placeholder="Password"
							name="senha" required>
					</div>

					<div class="submit">
						<input type="submit" value="Login">
					</div>
					<div class="clearfix"></div>

				</form>
			</div>
		</div>
	</div>

	<div class="footer"></div>
	<script
		src="<?php echo $this->baseUrl()?>/vendor/js/jquery.nicescroll.js"></script>
	<script src="<?php echo $this->baseUrl()?>/vendor/js/scripts.js"></script>
	<script src="<?php echo $this->baseUrl()?>/vendor/js/bootstrap.min.js"></script>
</body>
</html>
